server:
  port: 9081    # 추가된 부분

spring:
  datasource:
    url: ${MESSAGE_DB_URL}
    username: ${MESSAGE_DB_USERNAME}
    password: ${MESSAGE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000       # 5분
      max-lifetime: 600000       # 10분
      connection-timeout: 20000  # 20초
      validation-timeout: 5000
      connection-test-query: SELECT 1
      pool-name: HikariPool
      leak-detection-threshold: 30000  # 커넥션 누수 감지 (30초)
      auto-commit: false
      data-source-properties: # 추가: PostgreSQL 특정 설정
        reWriteBatchedInserts: true
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


message:
  processing:
    min-batch-size: 1000
    max-batch-size: 3000
    default-batch-size: 300
    min-threads: 1
    max-threads: 47
    default-threads: 10
    min-event-hub-batch: 50
    max-event-hub-batch: 500
    default-event-hub-batch: 100
    min-success-rate: 0
    max-success-rate: 100
    default-success-rate: 80

eventhub:
  connectionString: ${EVENTHUB_CONNECTION_STRING}

rcs:
  successRate: 98

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.rcs.external: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG    # SQL 쿼리 출력
    org.hibernate.type.descriptor.sql: TRACE  # SQL 쿼리 파라미터 값까지 출력
    org.springframework: WARN
    org.hibernate.orm.jdbc.bind: TRACE # 바인딩 파라미터 출력 (Hibernate 6.x 이상)
    com.azure.messaging.eventhubs: DEBUG    # Event Hub 상세 로깅
    com.rcs.external.service: DEBUG         # 서비스 레벨 로깅
