server:
  port: 9081    # 추가된 부분

spring:
  datasource:
    url: ${MESSAGE_DB_URL}
    username: ${MESSAGE_DB_USERNAME}
    password: ${MESSAGE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

message:
  processing:
    min-batch-size: 1000
    max-batch-size: 3000
    default-batch-size: 3000
    min-threads: 1
    max-threads: 47
    default-threads: 20
    min-event-hub-batch: 50
    max-event-hub-batch: 500
    default-event-hub-batch: 200
    min-success-rate: 0
    max-success-rate: 100
    default-success-rate: 80

eventhub:
  connectionString: ${EVENTHUB_CONNECTION_STRING}

rcs:
  successRate: 99

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.rcs.external: INFO