server:
  port: 9081    # 추가된 부분

spring:
  datasource:
    url: ${MESSAGE_DB_URL}
    username: ${MESSAGE_DB_USERNAME}
    password: ${MESSAGE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000        # 5분
      max-lifetime: 1200000       # 20분
      connection-timeout: 20000   # 20초
      validation-timeout: 5000    # 5초
      pool-name: HikariPool
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false   # 경고 제거를 위해 추가


message:
  processing:
    min-batch-size: 1000
    max-batch-size: 3000
    default-batch-size: 3000
    min-threads: 1
    max-threads: 47
    default-threads: 20
    min-event-hub-batch: 50
    max-event-hub-batch: 500
    default-event-hub-batch: 200
    min-success-rate: 0
    max-success-rate: 100
    default-success-rate: 80

eventhub:
  connectionString: ${EVENTHUB_CONNECTION_STRING}

rcs:
  successRate: 99

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.rcs.external: INFO