server:
  port: 9081    # 추가된 부분

spring:
  datasource:
    url: ${MESSAGE_DB_URL}
    username: ${MESSAGE_DB_USERNAME}
    password: ${MESSAGE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000       # 5분
      max-lifetime: 600000       # 10분 (기존 20분에서 줄임)
      connection-timeout: 20000
      validation-timeout: 5000
      connection-test-query: SELECT 1
      pool-name: HikariPool
      connection-init-sql: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    format_sql: true
    show-sql: true
    open-in-view: false   # 경고 제거를 위해 추가


message:
  processing:
    min-batch-size: 1000
    max-batch-size: 3000
    default-batch-size: 500
    min-threads: 1
    max-threads: 47
    default-threads: 10
    min-event-hub-batch: 50
    max-event-hub-batch: 500
    default-event-hub-batch: 100
    min-success-rate: 0
    max-success-rate: 100
    default-success-rate: 80

eventhub:
  connectionString: ${EVENTHUB_CONNECTION_STRING}

rcs:
  successRate: 99

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.rcs.external: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG    # SQL 쿼리 출력
    org.hibernate.type.descriptor.sql: TRACE  # SQL 쿼리 파라미터 값까지 출력
    org.springframework: WARN